[install]
exact = true
frozenLockfile = false

[install.lockfile]
print = "yarn"

[test]

coverage = true
preload = "./config/test/happyDom/index.ts"
coverageIgnoreSourcemaps = true
coverageThreshold = 0
